name: nightly build
env:
  DOCKER_SERVER: tip-tip-wlan-cloud-docker-repo.jfrog.io
  DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
  DOCKER_USER_PASSWORD: ${{ secrets.DOCKER_USER_PASSWORD }}
  TESTRAIL_USER_PASSWORD: ${{ secrets.TESTRAIL_USER_PASSWORD }}
  JFROG_USER_PASSWORD: ${{ secrets.JFROG_USER_PASSWORD }}
  AWS_EKS_NAME: tip-wlan-main
  AWS_DEFAULT_REGION: us-east-2
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_CLIENT_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_CLIENT_KEY }}

on:
  workflow_dispatch:
  schedule:
  - cron: '15 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout needed repositories
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: wlan-testing
    - name: Checkout LANforge scripts
      uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/wlan-lanforge-scripts
        token: ${{ secrets.GITHUB_TOKEN }}
        path: wlan-lanforge-scripts
    # build and push docker image
    - name: docker login
      shell: bash
      run: docker login ${{ env.DOCKER_SERVER }} -u ${{ env.DOCKER_USER_NAME }} -p ${{ env.DOCKER_USER_PASSWORD }}
    - name: build docker image
      shell: bash
      run: docker build -t ${{ env.DOCKER_SERVER }}/cloud-sdk-nightly:${{ github.run_id }} -f wlan-testing/docker/Dockerfile .
    - name: push docker image
      shell: bash
      run: docker push ${{ env.DOCKER_SERVER }}/cloud-sdk-nightly:${{ github.run_id }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: run tests
      run: |
        today=$(date +"%d-%m-%Y")
        aws eks update-kubeconfig  --name ${{ env.AWS_EKS_NAME }}
        cat <<EOF | kubectl apply -f -
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: nightly-ci-$today
        spec:
          template:
            labels:
              nightly: true
              date: $today
            spec:
              containers:
              - name: tests
                image: ${{ env.DOCKER_SERVER }}/cloud-sdk-nightly:${{ github.run_id }}
                args: 
                - "--testrail-user-password"
                - "${{ env.TESTRAIL_USER_PASSWORD }}"
                - "--jfrog-user-password"
                - "${{ env.JFROG_USER_PASSWORD }}"
                - "--skip-update-firmware"
              imagePullSecrets:
              - name: tip-docker-registry-key
              restartPolicy: Never
          backoffLimit: 0
        EOF
        kubectl wait job/nightly-ci-$today --for=condition=complete --timeout=3600s
        kubectl logs -l job-name=nightly-ci-$today
        kubectl delete job/nightly-$today
      shell: bash
