name: nightly build

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 4c74356b41/cloud-sdk-nightly
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: wlan-testing

    - name: Checkout LANforge scripts
      uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/wlan-lanforge-scripts
        token: ${{ secrets.GitHub_PAT }} # `GitHub_PAT` is a secret that contains your PAT
        path: wlan-LANforge-scripts
        
    - name: build docker image
      shell: bash
      run: ls -Rla; docker build -t tip/nightly -f wlan-testing/docker/Dockerfile
