name: nightly build

on: 
  workflow_dispatch:
  schedule:
    - cron: '15 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: wlan-testing

    - name: Checkout LANforge scripts
      uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/wlan-lanforge-scripts
        token: ${{ secrets.GITHUB_TOKEN }}
        path: wlan-LANforge-scripts
        
    - name: build docker image
      shell: bash
      run: docker build -t tip/nightly:${{ github.run_id }} -f wlan-testing/docker/Dockerfile .

    - name: run nightly tests
      shell: bash
      run: docker run cloud-sdk-nightly:${{ github.run_id }} --testrail-user-password ${{ secrets.TESTRAIL_USER_PASSWORD }} --jfrog-user-password ${{ secrets.JFROG_USER_PASSWORD }}
