name: nightly build

on: 
  workflow_dispatch:
  schedule:
    - cron: '15 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: wlan-testing

    - name: Checkout LANforge scripts
      uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/wlan-lanforge-scripts
        token: ${{ secrets.GITHUB_TOKEN }}
        path: wlan-LANforge-scripts
        
    - name: build docker image
      shell: bash
      run: |
        ls -Rla
        docker build -t tip/nightly -f wlan-testing/docker/Dockerfile .
